export const bubblegumTheme: any = {
    base: "vs-dark",
    inherit: false,
    rules: [
        { token: "", foreground: "C4C4C4", background: "#0A0A0A" },
        { token: "emphasis", fontStyle: "italic" },
        { token: "strong", fontStyle: "bold" },
        { token: "constant", foreground: "#E0E0E0" },
        { token: "comment", foreground: "#A0A0A0" },
        { token: "number", foreground: "#FFE96F" },
        { token: "type", foreground: "#FCA0EA" },
        { token: "attribute.value.hex.css", foreground: "#FFE96F" },
        { token: "string", foreground: "#FFE96F" },
        { token: "keyword", foreground: "#FFE96F" },
        
    ],
    colors: {
        "editor.background": "#0A0A0A",
        "editor.foreground": "#000000",
        "editor.selectionBackground": "#393939",
        "editor.lineHighlightBackground": "#FFFFFF0F",
        "editorCursor.foreground": "#FFFFFF",
        "editorWhitespace.foreground": "#FFFFFF0F",
        "editorBracketHighlight.foreground1": "#FFE96F",
		"editorBracketHighlight.foreground2": "#da70d6",
		"editorBracketHighlight.foreground3": "#AB9BFF",
        "focusBorder": "#FCA0EA",
        "errorForeground": "#cccccc",
        "editorSuggestWidget.background": "#0A0A0A",
		"editorSuggestWidget.border": "#454545",
		"editorSuggestWidget.focusHighlightForeground": "#FCA0EA",
		"editorSuggestWidget.foreground": "#cccccc",
		"editorSuggestWidget.highlightForeground": "#FCA0EA",
		"editorSuggestWidget.selectedBackground": "#323232",
		"editorSuggestWidget.selectedForeground": "#ffffff",
		"editorSuggestWidget.selectedIconForeground": "#ffffff",
		"editorSuggestWidgetStatus.foreground": "#cccccc80",
        "editor.findMatchHighlightBackground": "#393939",
        "inputOption.activeBorder": "#FCA0EA",
        
    },
};
